#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Self-Preprint PDF Generator with Physical Proof Cover Page (V1.2 Optimized)
利用 pandoc + xelatex 将 PREPRINTS/*.md 编译为包含防伪封面的学术 PDF。
包含：
  - LaTeX \tag{} 语法兼容补丁
  - YAML Frontmatter 重复剥离保护
  - CJK 中文字体参数精准转义
  - 临时文件自动安全清理
"""

import os
import sys
import json
import re
import subprocess
import glob
import tempfile
import shutil
from pathlib import Path
from datetime import datetime

# 路径配置
BASE_DIR = Path(__file__).resolve().parent.parent
PREPRINTS_DIR = BASE_DIR / "PREPRINTS"
REGISTRY_DIR = BASE_DIR / "CURRENCY_REGISTRY"
OUTPUT_PDF_DIR = BASE_DIR / "public" / "pdf"
SITE_URL = os.getenv("SITE_URL", "https://your-username.github.io/your-repo").rstrip("/")


def extract_metadata_and_body(md_content: str) -> tuple[dict, str]:
    """提取 YAML Frontmatter 元数据并返回剥离了 Frontmatter 的正文"""
    # 统一换行符
    content = md_content.replace("\r\n", "\n")
    meta = {}
    
    pattern = r"^---\s*\n(.*?)\n---\s*\n"
    match = re.search(pattern, content, re.DOTALL)
    
    if match:
        yaml_str = match.group(1)
        body = content[match.end():]
        for line in yaml_str.split("\n"):
            if ":" in line:
                k, v = line.split(":", 1)
                k = k.strip()
                v = v.strip().strip("\"'")
                meta[k] = v
    else:
        body = content

    return meta, body


def sanitize_latex_math(md_body: str) -> str:
    """
    预处理 Markdown 其中的 LaTeX 公式：
    将含有 \\tag{N} 的 $$ ... $$ 替换为 \\begin{equation} ... \\end{equation}
    避免 XeLaTeX 抛出 "LaTeX Error: \\tag not allowed here"
    """
    def replace_math_block(match):
        eq_content = match.group(1).strip()
        if r"\tag" in eq_content:
            return f"\n\\begin{{equation}}\n{eq_content}\n\\end{{equation}}\n"
        return f"\n$$\n{eq_content}\n$$\n"

    # 匹配 $$ ... $$ 块级公式
    return re.sub(r"\$\$\s*\n?(.*?)\n?\s*\$\$", replace_math_block, md_body, flags=re.DOTALL)


def load_currency_data(paper_id: str) -> dict:
    """从 CURRENCY_REGISTRY 加载防伪存证数据"""
    json_path = REGISTRY_DIR / f"{paper_id}.json"
    if json_path.exists():
        try:
            with open(json_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            print(f"⚠️ 读取存证 JSON 失败: {json_path} ({e})")
    return {"serial": "N/A", "hash": "N/A"}


def build_cover_md(paper_id: str, title: str, author: str, date_str: str, currency_data: dict) -> str:
    """生成防伪封面 Markdown (不带头部 YAML，防止与正文冲突)"""
    serial = currency_data.get("serial", "N/A")
    paper_hash = currency_data.get("hash", "N/A")

    return f"""# 🛡️ Physical Proof of Existence

**Title:** {title}  
**Author:** {author}  
**Date:** {date_str}  
**Banknote Serial:** `{serial}`  
**Paper SHA-256:** `{paper_hash}`  
**Verification URL:** [{SITE_URL}/preprints/{paper_id}.html]({SITE_URL}/preprints/{paper_id}.html)  

---

*This proof is automatically generated by the Self-Preprint system.*  
*© {datetime.now().year} {author} · Decentralized Academic Archive*

\\newpage
"""


def build_pdf(md_path: Path) -> bool:
    """单篇 PDF 编译 (含封面、正文清洗、附录拼接)"""
    paper_id = md_path.stem
    output_path = OUTPUT_PDF_DIR / f"{paper_id}.pdf"
    OUTPUT_PDF_DIR.mkdir(parents=True, exist_ok=True)

    # 1. 读取论文内容
    with open(md_path, "r", encoding="utf-8") as f:
        raw_content = f.read()

    meta, body = extract_metadata_and_body(raw_content)
    title = meta.get("title", paper_id)
    author = meta.get("author", meta.get("authors", "Anonymous"))
    date_str = str(meta.get("date", datetime.now().strftime("%Y-%m-%d")))

    # 2. 修复公式中的 \tag{} 兼容问题
    sanitized_body = sanitize_latex_math(body)

    # 3. 加载防伪存证数据
    currency_data = load_currency_data(paper_id)

    # 4. 生成封面与附录
    cover_md = build_cover_md(paper_id, title, author, date_str, currency_data)
    appendix_md = f"""

\\newpage

---

## Physical Proof of Existence (Appendix)

- **Banknote Serial:** `{currency_data.get('serial', 'N/A')}`
- **SHA-256 Hash:** `{currency_data.get('hash', 'N/A')}`
- **Verification URL:** [{SITE_URL}/preprints/{paper_id}.html]({SITE_URL}/preprints/{paper_id}.html)

*This document was timestamped via the Self-Preprint system.*
"""

    # 5. 合并为单一完整 Markdown 文稿，并在临时目录编译
    full_markdown = cover_md + "\n\n" + sanitized_body + "\n\n" + appendix_md

    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_md_path = Path(tmp_dir) / f"{paper_id}_combined.md"
        with open(tmp_md_path, "w", encoding="utf-8") as f:
            f.write(full_markdown)

        # 6. 构建 pandoc 命令
        cmd = [
            'pandoc',
            str(tmp_md_path),
            '--pdf-engine=xelatex',
            '-V', 'geometry:margin=1in',
            '-V', f'title={title}',
            '-V', f'author={author}',
            '-V', 'fontsize=11pt',
            '--toc',
            '--number-sections',
            f'--resource-path=.:{PREPRINTS_DIR}:{PREPRINTS_DIR / "images"}',
            '-o', str(output_path)
        ]

        # 如果包含中文字符，设置正确的 CJK 字体参数（无带转义字面引号）
        if re.search(r'[\u4e00-\u9fff]', raw_content):
            cmd.extend(['-V', 'CJKmainfont=Noto Sans CJK SC'])
            cmd.extend(['-V', 'CJKoptions=AutoFakeBold'])

        print(f"📄 正在编译 PDF: {paper_id}")
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=True,
                timeout=120
            )
            print(f"✅ PDF 生成成功: {output_path}")
            return True
        except subprocess.TimeoutExpired:
            print(f"❌ PDF 编译超时 (120s): {paper_id}")
            return False
        except subprocess.CalledProcessError as e:
            print(f"❌ PDF 编译失败: {paper_id}")
            if e.stdout:
                print(f"   STDOUT: {e.stdout[:500]}...")
            if e.stderr:
                print(f"   STDERR: {e.stderr[:500]}...")
            return False


def main():
    """批量编译所有 Markdown 论文"""
    if not shutil.which('pandoc'):
        print("❌ pandoc 未安装，请先安装: sudo apt-get install pandoc texlive-xetex fonts-noto-cjk")
        sys.exit(1)

    md_files = glob.glob(str(PREPRINTS_DIR / "*.md"))
    if not md_files:
        print("ℹ️ 未找到任何 .md 论文，跳过 PDF 生成。")
        return

    print(f"📂 找到 {len(md_files)} 篇论文，开始生成 PDF...\n")

    success_count = 0
    for md_path in md_files:
        if build_pdf(Path(md_path)):
            success_count += 1
        print("-" * 40)

    print(f"\n📊 总结：成功生成 {success_count}/{len(md_files)} 个 PDF 文件。")
    if success_count < len(md_files):
        print("⚠️ 部分 PDF 生成失败，请检查日志。")
        sys.exit(1)
    else:
        print("🎉 所有 PDF 均已成功生成！")


if __name__ == "__main__":
    main()
