#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Self-Preprint PDF Generator with Physical Proof Cover Page (English-only cover)
利用 pandoc + xelatex 将 PREPRINTS/*.md 编译为包含防伪封面的学术 PDF。
防伪封面为纯英文，避免 LaTeX 中文宏包依赖。
"""

import os
import sys
import json
import re
import subprocess
import glob
import tempfile
import shutil
from pathlib import Path
from datetime import datetime

# 路径配置
BASE_DIR = Path(__file__).resolve().parent.parent
PREPRINTS_DIR = BASE_DIR / "PREPRINTS"
REGISTRY_DIR = BASE_DIR / "CURRENCY_REGISTRY"
OUTPUT_PDF_DIR = BASE_DIR / "public" / "pdf"
SITE_URL = os.getenv("SITE_URL", "https://your-username.github.io/your-repo").rstrip("/")


def extract_metadata(md_content: str) -> dict:
    """提取 YAML Frontmatter 元数据"""
    meta = {}
    pattern = r"^---\s*\n(.*?)\n---\s*\n"
    match = re.search(pattern, md_content, re.DOTALL)
    if match:
        yaml_str = match.group(1)
        for line in yaml_str.split("\n"):
            if ":" in line:
                k, v = line.split(":", 1)
                k = k.strip()
                v = v.strip().strip("\"'")
                meta[k] = v
    return meta


def load_currency_data(paper_id: str) -> dict:
    """从 CURRENCY_REGISTRY 加载防伪存证数据"""
    json_path = REGISTRY_DIR / f"{paper_id}.json"
    if json_path.exists():
        try:
            with open(json_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            print(f"⚠️ 读取 JSON 失败: {json_path} ({e})")
    return {"serial": "N/A", "hash": "N/A"}


def build_cover_md(paper_id: str, title: str, author: str, date_str: str, currency_data: dict) -> str:
    """
    生成防伪封面 Markdown（纯英文，避免中文宏包依赖）
    """
    serial = currency_data.get("serial", "N/A")
    paper_hash = currency_data.get("hash", "N/A")
    # 显示前后缀便于核对
    hash_display = paper_hash if paper_hash != "N/A" else "N/A"
    if len(hash_display) > 16 and hash_display != "N/A":
        hash_display = f"{hash_display[:12]}...{hash_display[-8:]}"

    return f"""---
title: "Self-Preprint Physical Proof of Existence"
author: "Self-Preprint System"
date: "{date_str}"
---

# 🛡️ Physical Proof of Existence

**Title:** {title}

**Author:** {author}

**Date:** {date_str}

**Banknote Serial:** `{serial}`

**Paper SHA-256:** `{paper_hash}`

**Verification URL:** [{SITE_URL}/preprints/{paper_id}.html]({SITE_URL}/preprints/{paper_id}.html)

---

*This proof is automatically generated by the Self-Preprint system.*

*© {datetime.now().year} {author} · Decentralized Academic Archive*
"""


def build_pdf(md_path: Path) -> bool:
    """
    单篇 PDF 编译
    采用防伪封面（方式一）+ 正文附录（方式三）组合方案
    添加 --resource-path 确保图片能被找到
    """
    paper_id = md_path.stem
    output_path = OUTPUT_PDF_DIR / f"{paper_id}.pdf"
    OUTPUT_PDF_DIR.mkdir(parents=True, exist_ok=True)

    # 1. 读取论文内容和元数据
    with open(md_path, "r", encoding="utf-8") as f:
        content = f.read()

    meta = extract_metadata(content)
    title = meta.get("title", paper_id)
    author = meta.get("authors", "Anonymous")
    date_str = str(meta.get("date", datetime.now().strftime("%Y-%m-%d")))

    # 2. 加载防伪数据
    currency_data = load_currency_data(paper_id)

    # 3. 生成防伪封面（纯英文）
    cover_md = build_cover_md(paper_id, title, author, date_str, currency_data)
    cover_path = OUTPUT_PDF_DIR / f"{paper_id}_cover.md"
    with open(cover_path, "w", encoding="utf-8") as f:
        f.write(cover_md)

    # 4. 生成正文附录（方式三：在正文末尾追加防伪信息）
    appendix = f"""
---
## Physical Proof of Existence (Appendix)

- **Banknote Serial:** `{currency_data.get('serial', 'N/A')}`
- **SHA-256 Hash:** `{currency_data.get('hash', 'N/A')}`
- **Verification URL:** [{SITE_URL}/preprints/{paper_id}.html]({SITE_URL}/preprints/{paper_id}.html)

*This document was timestamped via the Self-Preprint system.*
"""
    appendix_path = OUTPUT_PDF_DIR / f"{paper_id}_appendix.md"
    with open(appendix_path, "w", encoding="utf-8") as f:
        f.write(appendix)

    # 5. 构建 pandoc 命令
    # 添加 --resource-path=.:PREPRINTS 让 pandoc 在根目录和 PREPRINTS 目录下搜索图片
    # 这样 Markdown 中的 "images/..." 路径就能正确解析
    cmd = [
        'pandoc',
        str(cover_path),          # 防伪封面
        str(md_path),             # 论文正文
        str(appendix_path),       # 防伪附录
        '--pdf-engine=xelatex',
        '-V', 'geometry:margin=1in',
        '-V', f'title={title}',
        '-V', f'author={author}',
        '-V', 'fontsize=11pt',
        '--toc',
        '--number-sections',
        '--resource-path=.:PREPRINTS',   # 关键：添加搜索路径
        '-o', str(output_path)
    ]

    # 检测是否包含中文字符（仅当论文正文或封面含中文时启用 CJK）
    # 但封面已是英文，若正文含中文则添加
    if re.search(r'[\u4e00-\u9fff]', content):
        cmd.extend(['-V', 'CJKmainfont="Noto Sans CJK SC"'])
        cmd.extend(['-V', 'CJKoptions="AutoFakeBold"'])

    print(f"📄 正在编译 PDF: {paper_id}")
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True,
            timeout=120  # 2 分钟超时
        )
        print(f"✅ PDF 生成成功: {output_path}")
        return True
    except subprocess.TimeoutExpired:
        print(f"❌ PDF 编译超时 (120s): {paper_id}")
        return False
    except subprocess.CalledProcessError as e:
        print(f"❌ PDF 编译失败: {paper_id}")
        if e.stdout:
            print(f"   STDOUT: {e.stdout[:500]}...")
        if e.stderr:
            print(f"   STDERR: {e.stderr[:500]}...")
        return False
    finally:
        # 清理临时文件
        for tmp in [cover_path, appendix_path]:
            if tmp.exists():
                tmp.unlink()


def main():
    """批量编译所有 Markdown 论文"""
    if not shutil.which('pandoc'):
        print("❌ pandoc 未安装，请先安装: sudo apt-get install pandoc texlive-xetex")
        sys.exit(1)

    md_files = glob.glob(str(PREPRINTS_DIR / "*.md"))
    if not md_files:
        print("ℹ️ 未找到任何 .md 论文，跳过 PDF 生成。")
        return

    print(f"📂 找到 {len(md_files)} 篇论文，开始生成 PDF...\n")

    success_count = 0
    for md_path in md_files:
        if build_pdf(Path(md_path)):
            success_count += 1
        print("-" * 40)

    print(f"\n📊 总结：成功生成 {success_count}/{len(md_files)} 个 PDF 文件。")
    if success_count < len(md_files):
        print("⚠️ 部分 PDF 生成失败，请检查日志。")
        sys.exit(1)
    else:
        print("🎉 所有 PDF 均已成功生成！")


if __name__ == "__main__":
    main()
